SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES;

-- 2)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID, LEVEL FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

-- 3)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID, LEVEL FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
ORDER BY LAST_NAME;

-- 4)
-- Level1 -> Level2 -> Level3...
--  Grandfather - Father - Son 
SELECT LAST_NAME, CONNECT_BY_ROOT LAST_NAME, 
LEVEL -1, SYS_CONNECT_BY_PATH(LAST_NAME, '->')
FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT LAST_NAME AS "WORKER", 
CONNECT_BY_ROOT LAST_NAME AS "MANAGER", 
LEVEL - 1 AS "LEVEL", 
SYS_CONNECT_BY_PATH(LAST_NAME, '->') AS "PATH"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 110 AND LEVEL > 1
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;
