-- making ORDER BY after query result
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID; -- we did'nt give any spesific grow condition so it will make it as ascending
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID ASC; -- this is equal to above 
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC; -- opposite to asc

SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC, SALARY ASC, JOB_ID; -- default order is ascending (asc)

SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL POSTA FROM EMPLOYEES ORDER BY MANAGER_ID; -- this will make order by manager it as asc (default)
-- manager_id is at 1. quoe
SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL POSTA FROM EMPLOYEES ORDER BY 1; -- this is equal to above
SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL POSTA FROM EMPLOYEES ORDER BY FIRST_NAME, LAST_NAME;
SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL POSTA FROM EMPLOYEES ORDER BY 2, 3; -- this is equal to above
SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL POSTA FROM EMPLOYEES ORDER BY 2 ASC, 3 DESC;

SELECT * FROM EMPLOYEES WHERE department_id = 90 ORDER BY SALARY; -- firstly where then order by